PUT http://localhost:3003/api/blogs/62691b83bdac4c23d1031d55
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyNjg1MGIxMzE2MWY5NTU1YTZhYTVmMCIsImlhdCI6MTY1MTA5MDI2MX0.PCxuu4fnbN-IN4vafcywI1TIxuu7A6A9FYhPI81OaAo

{
  "title": "First class tests",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
  "likes": 5,
  "user":"626850b13161f9555a6aa5f0"
}